version: '3'

env:
  PROJECT: clarum-go-binding
  VERSION: 1.0.0-snapshot
  AGENT_API_PATH: agent/api

tasks:
  version:
    cmds:
      - echo $VERSION

  build:
    cmds:
      - go build

  api:copy:
    deps: [ api:clean ]
    cmds:
      - |
        cp ../{{.AGENT_API_PATH}}/agent/*.go {{.AGENT_API_PATH}}/agent \
        && cp ../{{.AGENT_API_PATH}}/http/*.go {{.AGENT_API_PATH}}/http \
        && cp ../{{.AGENT_API_PATH}}/cmd/*.go {{.AGENT_API_PATH}}/cmd 

  api:clean:
    cmds:
      - |
        rm -rf {{.AGENT_API_PATH}} \
        && mkdir -p {{.AGENT_API_PATH}}/agent {{.AGENT_API_PATH}}/http/ {{.AGENT_API_PATH}}/cmd

  test:
    cmds:
      - go test ./...
