version: '3'

env:
  PROJECT: clarum-go-binding
  VERSION: 1.0.0-snapshot

tasks:
  version:
    cmds:
      - echo $VERSION

  build:
    cmds:
      - go build -o ./builds/{{.PROJECT}}-{{.VERSION}}

  agent:generate:
    deps: [ agent:build ]
    cmds:
      - mkdir -p builds/agent && cp agent/builds/clarum-agent-* builds/agent

  agent:update:
    cmds:
      - git submodule update --remote --merge

  agent:build:
    cmds:
      - cd agent && task build

  api:generate:
    deps: [ api:clean ]
    cmds:
      - |
        mkdir -p api && protoc --go_out=api --go_opt=paths=source_relative \
        --go-grpc_out=api --go-grpc_opt=paths=source_relative \
        agent/api/**/*.proto

  api:clean:
    cmds:
      - rm -rf api

  test:
    cmds:
      - go test ./...
